# Compose specification: https://docs.docker.com/compose/compose-file/

services:
  # elasticsearch: https://github.com/deviantony/docker-elk

  redis:
    image: redis
    #image: redis/redis-stack-server # FIXME: only works on amd64
    container_name: redis
    volumes:
      - ~/data/redis:/data
    networks:
      backend:
        aliases:
          - redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:oracle
    container_name: mysql
    volumes:
      - ~/data/mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: example

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      backend:
        aliases:
          - grafana
    ports:
      - "3000:3000"
    volumes:
      - ~/data/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      backend:
        aliases:
          - prometheus
    ports:
      - "9090:9090"
    volumes:
      - ~/data/prometheus/config:/etc/prometheus
      - ~/data/prometheus:/prometheus

networks:
  backend:
    name: backend
