services:
  # elasticsearch: https://github.com/deviantony/docker-elk

  mysql:
    image: mysql
    platform: linux/amd64
    container_name: mysql
    volumes:
      - $HOME/data/mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  redis:
    image: redis
    container_name: redis
    volumes:
      - $HOME/data/redis:/data
    networks:
      backend:
        aliases:
          - redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - $HOME/data/postgres:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=999"
  #      - "PGDATA=/var/lib/postgresql/data"

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      backend:
        aliases:
          - grafana
    ports:
      - "3000:3000"
    volumes:
      - $HOME/data/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      backend:
        aliases:
          - prometheus
    ports:
      - "9090:9090"
    volumes:
      - $HOME/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - $HOME/data/prometheus:/prometheus

networks:
  backend:
    name: backend
