version: "3.9"

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    volumes:
      - ~/data/mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=999

  redis:
    image: redis:6.2.5
    container_name: redis
    volumes:
      - ~/data/redis:/data
    networks:
      backend:
        aliases:
          - redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13.4
    container_name: postgres
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=999"

  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    volumes:
      - ~/data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      backend:
        aliases:
          - elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- "xpack.security.enabled=true"

  kibana:
    image: kibana:7.14.1
    container_name: kibana
    networks:
      backend:
        aliases:
          - kibana
    ports:
      - "5601:5601"
      #volumes:
      #- ~/data/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment: #https://www.elastic.co/guide/en/kibana/current/docker.html#docker-defaults
      #SERVER_NAME: kibana.example.org
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    networks:
      backend:
        aliases:
          - grafana
    ports:
      - "3000:3000"
    volumes:
      - ~/data/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    networks:
      backend:
        aliases:
          - prometheus
    ports:
      - "9090:9090"
    volumes:
      - ~/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ~/data/prometheus:/prometheus

networks:
  backend:
    name: backend
