# Compose specification: https://docs.docker.com/compose/compose-file/

name: dev

services:
  # elasticsearch: https://github.com/deviantony/docker-elk

  redis:
    image: redis/redis-stack
    container_name: redis-stack
    volumes:
      - redis:/data
    networks:
      backend:
        aliases:
          - redis
    ports:
      - 6379:6379
      - 8001:8001

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: 2zWHWfxyVV8gLFt+S03lGkWs07mHfOk4

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 2zWHWfxyVV8gLFt+S03lGkWs07mHfOk4

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      backend:
        aliases:
          - pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: c745539141@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 2zWHWfxyVV8gLFt+S03lGkWs07mHfOk4

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      backend:
        aliases:
          - grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      backend:
        aliases:
          - prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/etc/prometheus
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

networks:
  backend:
    name: backend

volumes:
  mysql:
  postgres:
  redis:
  grafana:
  prometheus:
  influxdb:
